sudo: true

language: python

os:
  - linux
  - osx

env:
  global:
    - TEST_WITH_XVFB=true
    - ENV_TYPE="conda"
    - ENV_DIR="${HOME}/envs"
    - EXTRA_WHEELS="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
    - PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
    - EXTRA_PIP_FLAGS="--timeout=60 --find-links=$EXTRA_WHEELS"

  matrix:
    - PY_VERSION="2.7"
    - PY_VERSION="3.5"
    - PY_VERSION="3.6"
    
# before_install:
#   - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
#   - sudo apt-get update -qq -y
#   - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev mesa-utils
#   - sudo apt-get install -y xvfb;
#   - pip install xvfbwrapper

# matrix:
#   include:
#     - python: 3.6
#       env: ENV_TYPE="pip"
#     - python: 3.6
#       env: OPTIONAL_DEPS=1 COVERAGE=1
#     - python: 3.6
#       env: ENV_TYPE="pip" OPTIONAL_DEPS=1
#     - python: 3.6
#       env: ENV_TYPE="pip" OPTIONAL_DEPS=1 USE_PRE=1
#   allow_failures:
#     - python: 3.6
#       env: ENV_TYPE="pip" OPTIONAL_DEPS=1 USE_PRE=1

install: bash ci/travis/install.sh
script: bash ci/travis/script.sh

# after_success:
#     - if [ "${COVERAGE}" == "1" ]; then coveralls; codecov; fi
#     - bash ci/travis/deploy_docs.sh


cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
