sudo: true
language: generic
dist: xenial
os:
- linux
- osx
addons:
  apt:
    sources:
    - sourceline: ppa:ubuntu-x-swat/updates
    - sourceline: ppa:oibaf/graphics-drivers
    update: true
    packages:
    - libglew-dev
    - freeglut3-dev
    - libxi-dev
    - libxmu-dev
    - xorg-dev
    - libgl1-mesa-dev
    - libgl1-mesa-glx
    - libglapi-mesa
    - libgl1-mesa-dri
    - libgbm1
    - libxatracker-dev
    - libxcursor-dev
    - libpulse-dev
    - libxinerama-dev
    - libxrandr-dev
    - libxv-dev
    - libasound2-dev
    - libudev-dev
    - mesa-utils
    - xvfb
    - mesa-common-dev
  homebrew:
    update: true
env:
  global:
  - MESA_GL_VERSION_OVERRIDE=3.3
  - TEST_WITH_XVFB=true
  - LIBGL_ALWAYS_INDIRECT=y
  - DISPLAY=:99
  - ENV_TYPE="conda"
  - ENV_DIR="${HOME}/envs"
  - EXTRA_WHEELS="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
  - PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
  - EXTRA_PIP_FLAGS="--timeout=60 --find-links=$EXTRA_WHEELS"
  - GH_REF: "github.com/fury-gl/fury-website.git"
  - GH_TOKEN:
      secure: "UZ0KrdPwzFg6rZG2YqHcPwfJsvJk2wOMaX+svZuK2YdYrLl4o3TBzw96Wg3wnaUc5dfwXPWqpisZg8HTrdT2/ntqXMXShZMmdcN79Zm2MEHTOd+Y3WS/f2gQaIt6U48/ttTKp3IXgtMsYLku5qAsJEBZ03LPT9L4dOy+tHz6RB6fQWdXYzyKzasu59EApH1NaYmxc0TED6d75KQ+AETx4yH7kYrAJ7aRSXbXGyDgtgEo9P9X0DJHakhbrxNgZPop4oEcLLzns4DMvkfrIrIJeZKb9JChZBja/6sWv3ZPmazmfhez7o+83x4pETUOlkzVUoiMfye6sDwJvm9AFi3u6OcmQ256oEj3/WnpZwZn2dAZ6CTAv0K9zfw8p2moLcAG9PFMRBOwtFN4IuT+3c31b7hca4nLJ6wp43XOZSRtzjA7o5ZmGmaiWukdFo7hCGG9p82CL9VoJ7y0ZWdh5kgzUkuXe01OjVcjiYhawWIzZbIBM2yR3czXMm5s+bjMPCBsLrPjHrjgqhmDUdEfEJUShriW7ORU7JoywgTf2dbMFzAPV5qHxb2h301LrB81C3UgSmMgXqJnkQg9yYnvpJfOJPeJeCdWxK6nVPJ2CfvbuZUwonf0BSIm2+hjkxwK0uKH32ZKW+7aBekQPxxJ83GimaZMXBjEGuTnI2QL9KsacdM="
  matrix:
  - PY_VERSION="2.7"
  - PY_VERSION="3.5"
  - PY_VERSION="3.6"
  - PY_VERSION="3.6" OPTIONAL_DEPS=1
  # - PY_VERSION="3.6" ENV_TYPE="pip"
  # - PY_VERSION="3.6" ENV_TYPE="pip" OPTIONAL_DEPS=1
matrix:
  allow_failures:
  - os: osx
  include:
  - os: linux
    env: PY_VERSION="3.6" OPTIONAL_DEPS=1 BUILD_DOCS=1 DEPLOY_DOCS=1
  - os: linux
    env: PY_VERSION="3.6" OPTIONAL_DEPS=1 COVERAGE=1
  # - os: linux
  #   env: PY_VERSION="3.6" ENV_TYPE="pip" OPTIONAL_DEPS=1 USE_PRE=1
install: bash ci/travis/install.sh
script: bash ci/travis/script.sh
after_success:
- if [ "${COVERAGE}" == "1" ]; then coveralls; codecov; fi
- bash ci/travis/deploy_docs.sh
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ccache"
