sudo: true

language: generic

dist: xenial

os:
  - linux
  - osx
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-x-swat/updates'
      - sourceline: 'ppa:oibaf/graphics-drivers'
    update: true
    packages:
      - libglew-dev
      - freeglut3-dev
      - libxi-dev
      - libxmu-dev
      - xorg-dev
      - libgl1-mesa-dev
      - libgl1-mesa-glx
      - libglapi-mesa
      - libgl1-mesa-dri
      - libgbm1
      - libxatracker-dev
      - libxcursor-dev
      - libpulse-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxv-dev
      - libasound2-dev
      - libudev-dev
      - mesa-utils
      - mesa-common-dev
      - libllvm7
      - xvfb
  homebrew:
    update: true
env:
  global:
    - TEST_WITH_XVFB=true
    - LIBGL_ALWAYS_INDIRECT=y
    - DISPLAY=:99
    - ENV_TYPE="conda"
    - ENV_DIR="${HOME}/envs"
    - EXTRA_WHEELS="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
    - PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
    - EXTRA_PIP_FLAGS="--timeout=60 --find-links=$EXTRA_WHEELS"
    - GH_REF: github.com/fury-gl/fury-website.git
    - secure: "soARGA/z9FMCu+ESVEheL3Ge+K8ezK2Um++cfbJAgS0qjUHeeIWY5/Bv1tagVNDEhQIcmCyNUK2lRyzomLrk6Rpkr2rOomu3sdadJ4/C3Tiz4izy1DVQDg481qUF4nVRH02Sx/mH2wDrbCvwtptkCydg97pP6ZnGyF3KHBbfKtGr/CKuEWorOYQ5wK8TCA9rajhtQTryCJjCw0ZbsQz9zjvIKQ2j8vl3+lAskCkzcw00t5rTxD6CiuJ6nwpmgKBfvj68NXwpTVgTLNhvQndn3zN5+dSi845YG3sZpXEcUQ00w0CN63o3E7wEkzoPBrmOaYpsuxKkoJ5b01ItpJfuFA7g7A0YSF2VaS0t3ZesmGsL7OE3x1MueFAsCGFDFF8/0GbUiFJlnMNwDezmd3W20NFuOI4XV7Iae8GueY+IMza7d7n6dValH2RGIC0rts9AQ6YrfxmxH2GHlI8EllJE87OvkdlkkJYjES1yBIAa5ATBxnpHGSl6ttSPlSLbI1IreDEJxNXaneR//6J2DWGAWLNnViq5pvIiM0nvTFmXklyaGnNj0//cHSry5tZF7DnF56iOXK/mv4r6aqyAWSTqPAIU6gqseRx5FXSdAMqUDCfuk6vxiq3aZOxnMUiSsReZ8le4SzZrJECWk/wAcDxkDOI2qsnFwz7H65VT26Eyan4="

  matrix:
    - PY_VERSION="2.7"
    - PY_VERSION="3.5"
    - PY_VERSION="3.6"
    - PY_VERSION="3.6" OPTIONAL_DEPS=1
    # - PY_VERSION="3.6" ENV_TYPE="pip"
    # - PY_VERSION="3.6" ENV_TYPE="pip" OPTIONAL_DEPS=1

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env: PY_VERSION="3.6" OPTIONAL_DEPS=1 COVERAGE=1
    - os: linux
      env: PY_VERSION="3.6" OPTIONAL_DEPS=1 BUILD_DOCS=1 DEPLOY_DOCS=1
    # - os: linux
    #   env: PY_VERSION="3.6" ENV_TYPE="pip" OPTIONAL_DEPS=1 USE_PRE=1

install: bash ci/travis/install.sh
script: bash ci/travis/script.sh

after_success:
    - if [ "${COVERAGE}" == "1" ]; then coveralls; codecov; fi
    - bash ci/travis/deploy_docs.sh


cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
